layouts/partials/menu-footer.html

Quick fix in the menu footer to the word Sustainable :)

Spelling fix

---

content/business-models/free-software-product.md

Spelling and comma

---

content/_index.md

Using a proper dash instead of its ASCII fallback.

Fix tiny typo

---

content/sfosc-book/business-models.md

Correct the intended spelling / word from "meed" to "meet".

Change "meed" to "meet"

---

content/business-models/as-a-service.md

WordPress is probably one of the most successful in this category, not listing them would be weird.

Added WordPress as example

---

content/sfosc-book/business-models.md

... to mention that Citrix released the XenServer code as open source
over time.  That said, I don't think that XenServer is a pure support
play, I think that it was always an open core play. Pure support plays
make me think of LinuxCare and SpikeSource.

Update the Xen / XenServer case study

---

content/sfosc-book/governance.md

See https://www.python.org/dev/peps/pep-8016/ for the new Python governance.

Note that Python is no longer a dictatorship

---

CONTRIBUTING.md

Help people that want to contribute to find their way around this project. The
commit/PR guidelines are (partly) based on https://github.com/rtbkit/rtbkit

Setup contribution guidelines

---

content/business-models/free-software-island.md
content/business-models/loose-open-core.md

A few typos made it through this otherwise-remarkable work.

Fix a couple of typos in principles and models

---

content/sfosc-book/business-models.md
content/sfosc-book/conception.md
content/sfosc-book/contribution_and_distribution.md
content/sfosc-book/governance.md
content/sfosc-book/institutions.md
content/sfosc-book/motivations.md
content/sfosc-book/rawls_for_foss.md
content/sfosc-book/the_way_forward.md

* Trims the whitespace
* Fixes a few typos
* Explicitly defines a few acronyms that were not easily searchable on their own
* Respect more of the 80 column that is happening
> A garden requires patient labor and attention. Plants do not grow merely to satisfy
> ambitions or to fulfill good intentions. They thrive because someone expended effort on them.
> ~ Liberty Hyde Bailey

Book: Small typos, 80 column adherence and white space

---

content/business-models/free-software-island.md

The word proprietary was spelled incorrectly. Side note: Great resource and explanation of open source models, which is why I was on the page! Thank you for putting this together.

free-software-island.md: fixed typo

---

MEMBERSHIP.md

Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>
hey maintainers! I'm an avid participant in open source software communities, and I'm interested in this effort and want to help if I can. The most straight forward thing seems to be (to start) adding my name to the MEMBERSHIP.md file. Understandably this just means getting a vote, and I'll also follow the repository to see how else I might contribute. Looking forward to it!

adding vsoch to membership file

---

content/business-models/free-software-island.md
content/business-models/loose-open-core.md

Add my name and Github ID to the membership file

Add my name to membership

---

content/sfosc-book/institutions.md

This pull request smooths out a sentence:
"all kinds of things: access, prestige, money." --> "all kinds of things, including: access, prestige, and money."
Signed-off-by: Georg J.P. Link <linkgeorg@gmail.com>

"all kinds of things: access, prestige, money." --> "all kinds of things, including: access, prestige, and money."

---

content/business-models/none.md

This PR mainly serves as a basis for discussion of this aspect for the sfosc.
A large portion (the majority?) of Free and Open Source projects uses this *"business model"* including a significant amount of core GNU/Linux infrastructure and tools, that have arguably the longest track record of being sustainable.
How does this fit into the whole concept/basis of sfosc?

Add a page about using no business model

---

MEMBERSHIP.md

As [pointed out](https://github.com/sfosc/sfosc/pull/54#issuecomment-491424989) I had not applied for membership yet.
Since I have received maintainer access as well in #60 I'll share a more detailed introduction while I start chipping away at some of the backlog.

Applying for membership

---

content/business-models/dual-licensing.md
content/business-models/support.md

Fix info on MySQL business model: it is primarily support

---

.gitmodules
config.preview.toml
deploy-preview.sh
deploy.sh
static/css/theme-sfosc.css
themes/hugo-theme-learn/layouts/partials/header.html

Adds a banner on top of every /preview page
Including a publish script as well to reproduce this more easily.

Preview banner

---

content/en/docs/Principles/_index.md

Alias the principles page to previous URL

---

content/en/docs/_index.md

Fix typo in referenced book url

---

content/en/docs/Business-Models/donations.md

Noticed in the links that this was wrong.
Urgent fix.

fix(spelling) dontation => donation

---

MEMBERSHIP.md

Recreated #130 because I'm basically stupid. :)

Add Pradyun as a member

---

content/en/docs/Business-Models/tight-open-core.md

Thanks @marclaporte for reporting this!

fix(symlink): tight open core

---

MEMBERSHIP.md

- Ranjib Dey , github: ranjib
- Have worked in chef, fedora and few other FOSS community. Currently, lead reef-pi  work (code + hardware + user & developer community ).

Adding myself in the members list
